sudo: false
dist: xenial
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before|install:
- sudo apt-get update
- sudo snap install dotnet-sdk --beta --classic
- sudo snap alias dotnet-sdk.dotnet dotnet
install:
- dotnet restore
script:
- dotnet build
- cd MangoTests
- dotnet test
