sudo: false
language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

install:
- dotnet restore
script:
- dotnet build
- cd MangoTests
- dotnet test
